myFile = open("texti.txt", "w")
myFile.write(input("Hvað viltu skrifa í texta skrána? "))
myFile.close()
myFile = open("texti.txt", "a")
myFile.write(input("Hvað viltu bæta við í þessari skrá? "))
myFile.write("Wow! That was very interesting. ")
myFile.write("That was pretty funny haha!")
myFile = open("texti.txt", "r")
print(myFile.read())
myFile.close()