skra = input("Hvað á skráin að heita?(Verður að enda með '.txt') ")
myFile = open(skra, "w+")
myFile.write(input("Hvað viltu skrifa í texta skrána? "))
myFile.close()
myFile = open(skra, "a")
myFile.write(input("Hvað viltu bæta við í þessari skrá? "))
myFile.write("Wow! That was very interesting. ")
myFile.write("That was pretty funny haha!")
myFile = open(skra, "r")
print(myFile.read())
myFile.close()